name: Deploy

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go run 4d63.com/vangen@latest -out=_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/configure-pages@v2
    - uses: actions/deploy-pages@v1
