name: Deploy

on:
  push:
    branches:
      main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1
    - run: go run 4d63.com/vangen@latest -out=build
    - uses: actions/upload-artifact@v2
      with:
        path: ./build
    - uses: actions/deploy-pages@v1-beta
